version : '3.7'

services:
    app:
      build: ./.docker
      working_dir: /var/www
      volumes:
        - .:/var/www:cached
        - ./.docker/php.ini:/usr/local/etc/php/conf.d/local.ini
      networks:
        - rest-network

    nginx:
      image: nginx:alpine
      ports:
        - "9000:8080"
      volumes:
        - .:/var/www:cached
        - ./.docker/app.conf:/etc/nginx/conf.d/app.conf
      networks:
        - rest-network

    redis:
      image: 'redis:alpine'
      ports:
        - '6384:6379'
      networks:
        - rest-network

networks:
  rest-network:
    driver: bridge
